Relocate prepare kerberos into config_generator

diff --git a/.evergreen/generated_configs/functions.yml b/.evergreen/generated_configs/functions.yml
--- a/.evergreen/generated_configs/functions.yml
+++ b/.evergreen/generated_configs/functions.yml
@@ -98,6 +98,27 @@ functions:
             for file in $(find .evergreen/scripts -type f); do
                 chmod +rx "$file" || exit
             done
+  prepare-kerberos:
+    - command: subprocess.exec
+      type: setup
+      params:
+        binary: bash
+        working_dir: mongoc
+        silent: true
+        args:
+          - -c
+          - |
+            if test "${keytab|}" && [[ -f /etc/krb5.conf ]]; then
+                echo "${keytab}" > /tmp/drivers.keytab.base64
+                base64 --decode /tmp/drivers.keytab.base64 > /tmp/drivers.keytab
+                if touch /etc/krb5.conf 2>/dev/null; then
+                    cat .evergreen/etc/kerberos.realm | tee -a /etc/krb5.conf
+                elif command sudo true 2>/dev/null; then
+                    cat .evergreen/etc/kerberos.realm | sudo tee -a /etc/krb5.conf
+                else
+                    echo "Cannot append kerberos.realm to /etc/krb5.conf; skipping." 1>&2
+                fi
+            fi
   release-archive:
     - command: subprocess.exec
       type: test
