CDRIVER-4677 conditionally restore AWS instance profile (#1410)
* add `restore-instance-profile` function

---------

Co-authored-by: Ezra Chung <88335979+eramongodb@users.noreply.github.com>

diff --git a/.evergreen/generated_configs/functions.yml b/.evergreen/generated_configs/functions.yml
--- a/.evergreen/generated_configs/functions.yml
+++ b/.evergreen/generated_configs/functions.yml
@@ -285,6 +285,36 @@ functions:
                     echo "Cannot append kerberos.realm to /etc/krb5.conf; skipping." 1>&2
                 fi
             fi
+  restore-instance-profile:
+    - command: subprocess.exec
+      params:
+        binary: bash
+        args:
+          - -c
+          - |
+            # Restore the AWS Instance Profile that may have been removed in AWS tasks.
+
+            if [[ ! -d drivers-evergreen-tools ]]; then
+                echo "drivers-evergreen-tools not present ... skipping"
+                exit 0
+            fi
+
+            cd drivers-evergreen-tools/.evergreen/auth_aws
+            if [[ ! -f aws_e2e_setup.json ]]; then
+                echo "aws_e2e_setup.json not present ... skipping"
+                exit 0
+            fi
+
+            . ./activate-authawsvenv.sh
+
+            echo "restoring instance profile ... "
+            # Capture and hide logs on success. Logs may included expected `HTTP Error 404: Not Found` messages when checking for instance profile.
+            if ! { python ./lib/aws_assign_instance_profile.py 2>&1 >|output.txt; }; then
+                echo "restoring instance profile ... failed"
+                cat output.txt 1>&2
+                exit 1
+            fi
+            echo "restoring instance profile ... succeeded"
   run-mock-kms-servers:
     - command: subprocess.exec
       type: setup
