CDRIVER-3882 Support AWS temporary credentials (#1109)
* Sync legacy CSE test files with b3beada7

* Add legacy CSE test runner support for AWS temp creds

* Update Evergreen config to support AWS temp creds

* Print status during invocation of Drivers Evergreen Tools scripts

* Define PYTHON as PYTHON_BINARY after activate_venv.sh

* Deactivate the kmstlsenv venv environment when done

* Ensure calls to activate_venv.sh do not race on venv preparation

* Replace legacy backtick notation with dollar-parenthesis notation

* Suppress errors on chmod of build dirs

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -427,16 +427,38 @@ functions:
         export DNS=${DNS}
         export ASAN=${ASAN}
         export CLIENT_SIDE_ENCRYPTION=${CLIENT_SIDE_ENCRYPTION}
-        # Hide credentials.
-        set +o xtrace
-        set +o errexit
         # Only set creds if testing with Client Side Encryption.
         # libmongoc may build with CSE enabled (if the host has libmongocrypt installed)
         # and will try to run those tests (which fail on ASAN unless spawning is bypassed).
         if [ -n "$CLIENT_SIDE_ENCRYPTION" ]; then
-          echo "testing with CSE"
-          export MONGOC_TEST_AWS_SECRET_ACCESS_KEY="${client_side_encryption_aws_secret_access_key}"
-          export MONGOC_TEST_AWS_ACCESS_KEY_ID="${client_side_encryption_aws_access_key_id}"
+          # Avoid printing credentials in logs.
+          set +o xtrace
+          echo "Testing with Client Side Encryption enabled."
+          echo "Setting temporary credentials..."
+          pushd ../drivers-evergreen-tools/.evergreen/csfle
+          export AWS_SECRET_ACCESS_KEY="${client_side_encryption_aws_secret_access_key}"
+          export AWS_ACCESS_KEY_ID="${client_side_encryption_aws_access_key_id}"
+          export AWS_DEFAULT_REGION="us-east-1"
+          echo "Running activate_venv.sh..."
+          . ./activate_venv.sh
+          echo "Running activate_venv.sh... done."
+          echo "Running set-temp-creds.sh..."
+          PYTHON="$(type -P python)" . ./set-temp-creds.sh
+          echo "Running set-temp-creds.sh... done."
+          deactivate
+          popd
+          echo "Setting temporary credentials... done."
+          # Ensure temporary credentials were properly set.
+          if [ -z "$CSFLE_AWS_TEMP_ACCESS_KEY_ID" ]; then
+            echo "Failed to set temporary credentials!"
+            exit 1
+          fi
+          echo "Setting KMS credentials from the environment..."
+          export MONGOC_TEST_AWS_TEMP_ACCESS_KEY_ID="$CSFLE_AWS_TEMP_ACCESS_KEY_ID"
+          export MONGOC_TEST_AWS_TEMP_SECRET_ACCESS_KEY="$CSFLE_AWS_TEMP_SECRET_ACCESS_KEY"
+          export MONGOC_TEST_AWS_TEMP_SESSION_TOKEN="$CSFLE_AWS_TEMP_SESSION_TOKEN"
+          export MONGOC_TEST_AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
+          export MONGOC_TEST_AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
           export MONGOC_TEST_AZURE_TENANT_ID="${client_side_encryption_azure_tenant_id}"
           export MONGOC_TEST_AZURE_CLIENT_ID="${client_side_encryption_azure_client_id}"
           export MONGOC_TEST_AZURE_CLIENT_SECRET="${client_side_encryption_azure_client_secret}"
@@ -444,6 +466,7 @@ functions:
           export MONGOC_TEST_GCP_PRIVATEKEY="${client_side_encryption_gcp_privatekey}"
           export MONGOC_TEST_CSFLE_TLS_CA_FILE=../drivers-evergreen-tools/.evergreen/x509gen/ca.pem
           export MONGOC_TEST_CSFLE_TLS_CERTIFICATE_KEY_FILE=../drivers-evergreen-tools/.evergreen/x509gen/client.pem
+          echo "Setting KMS credentials from the environment... done."
         fi
         export LOADBALANCED=${LOADBALANCED}
         export SINGLE_MONGOS_LB_URI="${SINGLE_MONGOS_LB_URI}"
@@ -776,6 +799,21 @@ functions:
   run kms servers:
   - command: shell.exec
     params:
+      shell: bash
+      script: |-
+        set -o errexit
+        echo "Preparing CSFLE venv environment..."
+        cd ./drivers-evergreen-tools/.evergreen/csfle
+        # This function ensures future invocations of activate_venv.sh conducted in
+        # parallel do not race to setup a venv environment; it has already been prepared.
+        # This primarily addresses the situation where the "run tests" and "run kms servers"
+        # functions invoke 'activate_venv.sh' simultaneously.
+        # TODO: remove this function along with the "run kms servers" function.
+        . ./activate_venv.sh
+        deactivate
+        echo "Preparing CSFLE venv environment... done."
+  - command: shell.exec
+    params:
       background: true
       shell: bash
       script: |-
@@ -788,6 +826,7 @@ functions:
         python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/wrong-host.pem --port 9001 &
         python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/server.pem --require_client_cert --port 9002 &
         python -u kms_kmip_server.py &
+        deactivate
         echo "Starting mock KMS servers... done."
   start load balancer:
   - command: shell.exec
