Better documentation on the __tool script

diff --git a/tools/__tool b/tools/__tool
--- a/tools/__tool
+++ b/tools/__tool
@@ -2,6 +2,24 @@
 
 # shellcheck disable=SC3043
 
+true <<EOF
+    This script is inteded for use with preparing a container environment, providing
+    a pile of common utilities that are useful for environment setup and management.
+
+    Basic usage:
+
+        __tool <subcommand> [args...]
+
+    where "<subcommand>" is any top-level function in this file.
+
+    The special '__init' subcommand installs several system-wide aliases for
+    common subcommands that are available in this file.
+
+    Running __init or __alias requires permission to install files into '/usr/local'.
+    Other commands, except for package management ones, do not require any special
+    permissions.
+EOF
+
 set -eu
 
 __init() {
@@ -18,68 +36,26 @@ __init() {
     __alias __str          __tool __str
 }
 
-# Usage: __readvar <dest> <varname>
-# Read the value of the variable named by <varname> into a variable <dest>
-__readvar() {
-    local __readvar_tmp
-    eval "__readvar_tmp=\$(printf %s. \"\${$2}\"); $1=\${__readvar_tmp%.}"
-}
-
+# ? __fail <f-string> [args...]
+#   This formats the given arguments using shell `printf` and writes the message
+#   to stderr, then immediately returns 1.
 __fail() {
     # shellcheck disable=SC2059
-    printf "$@"
+    printf "$@" 1>&2
     return 1
 }
 
-# $ __strsub_inplace <varname> <needle> <repl>
-# Replace each occurrence of <needle> with <repl> within the string variable <varname>
-__strsub_inplace() {
-    test $# -eq 3 || __fail "__strsub_inplace expects three arguments (Got %s)" $# || return
-    local __strsub_varname="$1" __strsub_needle="$2" __strsub_repl="$3"
-    # Read the value of <varname> into __strsub_remaining
-    __readvar __strsub_remaining "$__strsub_varname"
-    # Accumulate into __strsub_acc
-    local __strsub_head __strsub_acc=''
-    while true; do
-        # Grab all content until the next needle:
-        __strsub_head=${__strsub_remaining%%"$__strsub_needle"*}
-        if test "$__strsub_head" = "$__strsub_remaining"; then
-            # Nothing match the needle, so we are done
-            __strsub_acc="$__strsub_acc$__strsub_remaining"
-            break
-        fi
-        # Everything after the needle:
-        __strsub_remaining=${__strsub_remaining#*"$__strsub_needle"}
-        # Accumulate the result:
-        __strsub_acc="$__strsub_acc$__strsub_head$__strsub_repl"
-    done
-    # Read the accumulated string back into the output variable:
-    __readvar "$__strsub_varname" __strsub_acc
-}
-
-_ESCAPES="$(printf '[][ \t\n\r\a*?!\\\$;()\\{\\}'"'"']')"
-__quote() {
-    local __quote_input="$1"
-    # shellcheck disable=SC2295
-    local __quote_tmp="${__quote_input#*$_ESCAPES}" || return
-    if test "$__quote_input" = ""; then
-        # Empty string: Just emit empty quotes
-        printf '""'
-        return
-    elif test "$__quote_tmp" = "$__quote_input"; then
-        # No special chars, so don't quote it:
-        printf %s "$__quote_input"
-        return
-    else
-        # Special chars. Escape any inner quotes, then wrap in quotes
-        __strsub_inplace __quote_input "'" "'\\''"
-        printf "'%s'" "$__quote_input"
-    fi
-}
-
+# ? __alias <name> [command...]
+#   This subcommand will generate a system-wide persistent subcommand alias by
+#   the name `<name>`, installed in `/usr/local/bin`. The generated alias will
+#   execute the given `[command...]`. Any arguments passed to the generated alias
+#   command will be forwarded on to the underlying command cleanly.
+#
+#   No special quoting should be used for `command`.
 __alias() {
     command='' name="$1"
     shift
+    # Append each argument to the command with proper quoting
     for x in "$@"; do
         x=$(__quote "$x") || return
         command="$command$x "
@@ -93,8 +69,12 @@ __alias() {
     echo "Created command alias '$filename' of [$command]" 1>&2 || return
 }
 
+# ? __bool <b>
+#   Evaluate a string `<b>` as a boolean, returning zero if it is truthy. This
+#   follows the same truthy-ness rules as CMake, and is case-insensitive.
 __bool() {
-    bool=$(echo "$1" | __str upper)
+    # Normalize the case of the passed argument
+    bool=$(echo "${1-}" | __str upper)
     case "$bool" in
         0|OFF|NO|FALSE|N|IGNORE|NOTFOUND|""|*-NOTFOUND)
             return 1;;
@@ -103,6 +83,9 @@ __bool() {
     esac
 }
 
+# ? __boolstr <b>
+#   As with `__bool`, but instead of returning 0/1, it will print the word `true`
+#   or `false` to stdout, and always returns 0
 __boolstr() {
     if __bool "$@"; then
         printf "true"
@@ -111,10 +94,16 @@ __boolstr() {
     fi
 }
 
+# ? __have_command <cmd>
+#   Test whether the command `<cmd>` can be executed by the shell, regardless of
+#   the underlying command type. Returns 0 if-and-only-if the command can be executed.
 __have_command() {
     __silently type "$1"
 }
 
+# ? __do <message> [command...]
+#   Print `<message>`, and execute `command` silently, only printing its output
+#   if it exits non-zero.
 __do() {
     printf '%s\n' "$1"
     shift
@@ -127,17 +116,17 @@ __do() {
     fi
 }
 
-# Install the named packages using the platform's package manager.
-# This script "just does the right thing" to install a package as a step in a
-#   caching container build, as a bare "pkg-tool install" might be insufficient
-#   or subtly broken, and we only really care about installing a list of packages
-#
-# Usage: <script> [pkgs...]
+# ? __install [pkgs...]
+#   Installs zero or more named packages using the platform's package manager.
+#   This script "just does the right thing" to install a package as a single step,
+#   primarily to improve caching and reliability in a container image build, as a bare
+#   "pkg-tool install" might be insufficient or subtly broken, and we only really
+#   care about installing a list of packages
 __install() {
     if test -f /etc/debian_version ; then
         # We *must* do a repo update as part of the install step in a single cache
-        # layer, as a cached apt-get update can become stale while a later
-        # apt-get install is invalidated
+        # layer, as a cached apt-get update can become stale and prevent a later
+        # apt-get install from working properly
         apt-get -y update || return
         # DEBIAN_FRONTEND suppresses all interactivity. For some reason some
         # packages like to prompt as part of their config, even if we're not on
@@ -173,6 +162,8 @@ __install() {
     fi
 }
 
+# ? __can_install [pkgs...]
+#   Test whether it is possible to install all of the given packages with the system package manager
 __can_install() {
     # Refresh local package databases
     if test -f /etc/debian_version; then
@@ -208,18 +199,20 @@ __can_install_1() {
     elif test -f /etc/alpine-release; then
         __silently apk info -- "$package"
         return
+    elif __have_command zypper; then
+        __silently zypper info -- "$package"
+        return
     else
         echo "$0: We don't know how to manage packages on this system" 1>&2
         return 1
     fi
 }
 
+# ? __silently [command...]
+#   Execute the given shell command, but do it silently, supressing all output no
+#   matter what.
 __silently() {
     "$@" > /dev/null 2>&1
-}
-
-__purpose() {
-    __str test "${PURPOSE:-unset}" -matches "$1"
 }
 
 __STR_HELP='Usage:
@@ -304,6 +297,59 @@ __str__test() {
       # Just defer to the underlying test command
       test "$lhs" "$op" "$rhs"
   esac
+}
+
+# $ __strsub_inplace <varname> <needle> <repl>
+# Replace each occurrence of <needle> with <repl> within the string variable <varname>
+__strsub_inplace() {
+    test $# -eq 3 || __fail "__strsub_inplace expects three arguments (Got %s)" $# || return
+    local __strsub_varname="$1" __strsub_needle="$2" __strsub_repl="$3"
+    # Read the value of <varname> into __strsub_remaining
+    __readvar __strsub_remaining "$__strsub_varname"
+    # Accumulate into __strsub_acc
+    local __strsub_head __strsub_acc=''
+    while true; do
+        # Grab all content until the next needle:
+        __strsub_head=${__strsub_remaining%%"$__strsub_needle"*}
+        if test "$__strsub_head" = "$__strsub_remaining"; then
+            # Nothing match the needle, so we are done
+            __strsub_acc="$__strsub_acc$__strsub_remaining"
+            break
+        fi
+        # Everything after the needle:
+        __strsub_remaining=${__strsub_remaining#*"$__strsub_needle"}
+        # Accumulate the result:
+        __strsub_acc="$__strsub_acc$__strsub_head$__strsub_repl"
+    done
+    # Read the accumulated string back into the output variable:
+    __readvar "$__strsub_varname" __strsub_acc
+}
+
+_ESCAPES="$(printf '[][ \t\n\r\a*?!\\\$;()\\{\\}'"'"']')"
+__quote() {
+    local __quote_input="$1"
+    # shellcheck disable=SC2295
+    local __quote_tmp="${__quote_input#*$_ESCAPES}" || return
+    if test "$__quote_input" = ""; then
+        # Empty string: Just emit empty quotes
+        printf '""'
+        return
+    elif test "$__quote_tmp" = "$__quote_input"; then
+        # No special chars, so don't quote it:
+        printf %s "$__quote_input"
+        return
+    else
+        # Special chars. Escape any inner quotes, then wrap in quotes
+        __strsub_inplace __quote_input "'" "'\\''"
+        printf "'%s'" "$__quote_input"
+    fi
+}
+
+# Usage: __readvar <dest> <varname>
+# Read the value of the variable named by <varname> into a variable <dest>
+__readvar() {
+    local __readvar_tmp
+    eval "__readvar_tmp=\$(printf %s. \"\${$2}\"); $1=\${__readvar_tmp%.}"
 }
 
 cmd=$1
